### ISSUE TITLE
Webmachine resource for stats

### ISSUE THREAD

**Issue by kellymclaughlin** [basho/riak_cs#145]
Use the dss-stats1 branch as a base and create a resource so the stats information can be retrieved via HTTP.

**Comment by slfritchie** [comment]
I'm using `gh145-stats-and-webmachine` as the branch for this ticket.

At the moment, I'm stuck because I don't know enough Webmachine magic to make "GET /stats HTTP/1.0" work when talking to RCS's HTTP server ... and I'm not all that certain that we really want to expose the stats in the same way that we do for Riak.

AFAICT, as things are implemented right now, a GET request for "/stats" tries to make an anonymous inquiry into the S3 bucket "stats".  If we want "GET /stats" to avoid an S3 bucket, then we'd need to make certain RCS and stanchion never allow a user to create an S3 bucket called stats.  Er, or whatever the `app.config` says is the prefix for stats, because I've ripped off the Riak KV way of doing things:

Webmachine doodad to spit out a message if HTTP stats are completely disabled:

```
src/riak_cs_wm_stats.erl:    case riak_moss_utils:get_env(riak_moss, riak_cs_stat, false) of
```

Webmachine routing thingie:

```
src/riak_moss_web.erl:    [{prefix, riak_moss_utils:get_env(riak_moss, stats_urlpath, "stats")}].
```

Given all of this headache, I'm thinking that we want to expose these stats in some other manner.  For example, listen for connections on TCP port X, accept connection on that port, spit out some JSON, then close the connection & repeat.

... But there isn't enough guidance in this ticket for me to tackle either option.  I'll try to strike up a discussion on Friday morning.

**Comment by slfritchie** [comment]
https://github.com/basho/riak_moss/pull/188

**Comment by slfritchie** [comment]
https://github.com/basho/stanchion/pull/14

**Comment by slfritchie** [comment]
Note: use https://gist.github.com/cf4b264128097f0a80d6 as a basic script to try to trigger all stats counters to be incremented.

**Comment by slfritchie** [comment]
Review & rereview is nibbling quibbles down to nearly zero.  We'll stay with folsom for now but with a sharp eye on eliminating it with Russell's stats stuff as soon as feasible.

**Comment by slfritchie** [comment]
.
