### ISSUE TITLE
Paused GC and tried to resume to no avail [JIRA: RCS-353]

### ISSUE THREAD

**Issue by densone** [basho/riak_cs#329]
I paused gc for a few minutes, then resumed. Ring traffic never picked backup.  I ran gc status and noticed after over 10 minutes that no new files were deleted or skipped.

I was able to reproduce this issues 2 times in a row. For some reason GC is being kept from resuming. If I cancel and batch again. It works.

**Comment by reiddraper** [comment]
I've been able to repro. Working on a fix now.

**Comment by reiddraper** [comment]
A couple of notes on the current implementation that is making this fix more difficult than first imagined:

The FSM currently performs blocking (and non-deterministic) operations, which can cause delays when responding to messages like `status` (one of the observability commands). To prevent two of these operations from happening in a row, the FSM sends itself `continue` messages to give itself a chance to respond to external events. This complicates the FSM, and current has a couple bugs around receiving it's own continue messages. In order to clean things up and make correctly handing pause/resume easier, I suggest we take an approach similar to the GET/PUT FSM, and have a separate process that is the 'gc server'. It will serve as a wrapper around `riakc_pb_socket` operations. The result of these operations will come back as asynchronous messages to the daemon. Fortunately, the current GC daemon code is well-factored, so any refactoring should be able to share a majority of the helper functions and skeleton. Since this bug is not a blocker (there is an easy work-around by cancel/start-batch), I suggest we wait until we decide to address #579 before tackling this).

**Comment by shino** [comment]
I will close this if #881 is solved.

**Comment by kuenishi** [comment]
#881 was solved and its now 2.1 era.
