### ISSUE TITLE
GC daemon on/off switches [JIRA: RCS-343]

### ISSUE THREAD

**Issue by slfritchie** [basho/riak_cs#513]
It's a known feature that the Riak CS GC daemon is configured on for all CS nodes by default.  Having the GC daemon run simultaneously (which does indeed happen if many CS apps are started at the same time) isn't harmful from a data point of view, but it can create a lot of extra load on Riak than necessary.

**Comment by kellymclaughlin** [comment]
You can already effectively do this by setting `gc_interval` to `infinity`, but maybe a way to even prevent the daemon process from running at all would also be good.

**Comment by slfritchie** [comment]
Right -- I was thinking more along the line of restricting the total number of GC daemons running at a time cluster-wide, vis a vis Reid's writeup of pre-release issues a couple weekends ago.

**Comment by reiddraper** [comment]
Since we already have things like `anonymous_user_creation` default to false, needing you to manually set it to `true` once to get an admin user, I'm wondering if we shouldn't default the gc daemon to do the same. Have setting it on one node be part of the install process. Long term, we should be able to use the strong consistency work that will later land in Riak as a means to coordinate which Riak CS proc is currently doing GC. Thoughts?

**Comment by shino** [comment]
Repo cleanup sweeping.
It seems this PR is stale and has been address by doc.
I will close it but please feel free to re-open.
