### ISSUE TITLE
riak_cs_kv_mutlibackend does not support index_reformat

### ISSUE THREAD

**Issue by joecaswell** [basho/riak_cs#572]
riak_cs_kv_multibackend does not report index_reformat in its capabilities, and does not forward the command to reformat indexes to the underlying eleveldb backend.  This causes the index upgrade command to log an error for each partition:
[error] <0.210.0>@riak_kv_vnode:handle_command:588 Backend riak_cs_kv_multi_backend does not support incorrect index query
ref zd:4603

**Comment by reiddraper** [comment]
Some notes for myself as I start working on this:

The original import of `riak_cs_kv_multi_backend.erl` appears to be based on basho/riak_kv@a91c110d4f609e0e8632cd4bd6057aa10a93e406.

The relevant changes added to `riak_kv_multi_backend` since that fork are:

basho/riak_kv@f2c82db82743860aa05099c506b8e67143f09800
basho/riak_kv@58170cdf00033d23e553ff9103ee3027f708be45
basho/riak_kv@371f48066eab05301b8aea4df12eb408c4aadf48
basho/riak_kv@3e1ec4348e320754ac7f9db3805ec82aacbe365c
basho/riak_kv@b50d1df73aee20c4260e72d73fdfcf6493603636

as seen by `git log 1.3.0..HEAD -s -p src/riak_kv_multi_backend.erl` in the `riak_kv` repo.
